// auto-generated by generate_ast.go. DO NOT EDIT
package lox

type Expr interface {
Eval() (interface{}, *RuntimeError)
}
type Assign struct {
  name Token
  value Expr
}

type Binary struct {
  left Expr
  operator Token
  right Expr
}

type Grouping struct {
  expression Expr
}

type Literal struct {
  value interface{}
}

type Unary struct {
  operator Token
  right Expr
}

type Variable struct {
  name Token
}

