// auto-generated by generate_ast.go. DO NOT EDIT
package lox

type Expr interface {
Eval() (interface{}, *RuntimeError)
}
type Assign struct {
  name Token
  value Expr
}

type Binary struct {
  left Expr
  operator Token
  right Expr
}

type Call struct {
  callee Expr
  paren Token
  arguments []Expr
}

type Get struct {
  object Expr
  name Token
}

type Grouping struct {
  expression Expr
}

type Literal struct {
  value interface{}
}

type Logical struct {
  left Expr
  operator Token
  right Expr
}

type Set struct {
  object Expr
  name Token
  value Expr
}

type This struct {
  keyword Token
}

type Unary struct {
  operator Token
  right Expr
}

type Variable struct {
  name Token
}

