// auto-generated by generate_ast.go. DO NOT EDIT
package lox

type Stmt interface {
Execute() (interface{}, *RuntimeError)
}
type Block struct {
  statements []Stmt
}

type Expression struct {
  expression Expr
}

type Print struct {
  expression Expr
}

type Var struct {
  initializer Expr
  name Token
}
