// auto-generated by generate_ast.go. DO NOT EDIT
package lox

type Stmt interface {
Execute() (interface{}, *RuntimeError)
}
type Block struct {
  statements []Stmt
}

type Expression struct {
  expression Expr
}

type If struct {
  condition Expr
  thenBranch Stmt
  elseBranch Stmt
}

type Print struct {
  expression Expr
}

type Var struct {
  initializer Expr
  name Token
}

type While struct {
  condition Expr
  body Stmt
}

type Break struct {
  
}

